// tslint:disable
/**
 * UAP-Core Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TaskReport } from "./task-report.model";



/**
 * @export
 * @interface AssessmentReportResponse
 */
export interface AssessmentReportResponse {
    /**
     * Unique Report Id
     * @type {string}
     * @memberof AssessmentReportResponse
     */
    id?: string;
    /**
     * Unique Assessment Id
     * @type {string}
     * @memberof AssessmentReportResponse
     */
    assessmentId?: string;
    /**
     * Assessment Start Time
     * @type {string}
     * @memberof AssessmentReportResponse
     */
    startTime?: string;
    /**
     * Assessment End Time
     * @type {string}
     * @memberof AssessmentReportResponse
     */
    endTime?: string;
    /**
     * Assessment Completion Time
     * @type {string}
     * @memberof AssessmentReportResponse
     */
    completedTime?: string;
    /**
     * Assessment Status
     * @type {string}
     * @memberof AssessmentReportResponse
     */
    status?: string;
    /**
     * Assessment Mentor
     * @type {string}
     * @memberof AssessmentReportResponse
     */
    assignedBy?: string;
    /**
     * Assessment Level Consolidated Score
     * @type {string}
     * @memberof AssessmentReportResponse
     */
    consolidatedScore?: string;
    /**
     * @type {Array<TaskReport>}
     * @memberof AssessmentReportResponse
     */
    taskResults?: Array<TaskReport>;
}
