// tslint:disable
/**
 * UAP-Core Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Task status update
 * @export
 * @interface AssessmentTaskRequest
 */
export interface AssessmentTaskRequest {
    /**
     * Task Id
     * @type {string}
     * @memberof AssessmentTaskRequest
     */
    taskId?: string;
    /**
     * Task Status
     * @type {string}
     * @memberof AssessmentTaskRequest
     */
    status?: string;
    /**
     * Task Started At
     * @type {string}
     * @memberof AssessmentTaskRequest
     */
    startedDateTime?: string;
    /**
     * Task Completed At
     * @type {string}
     * @memberof AssessmentTaskRequest
     */
    completedDateTime?: string;
}
