// tslint:disable
/**
 * UAP-Core Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaginationModel } from "../../common/models/pagination.model";

/**
 * Assessment Create/Update Object
 * @export
 * @interface AssessmentRequest
 */
export interface AssessmentRequest {
    /**
     * Unique batch id to group individual assessments
     * @type {string}
     * @memberof AssessmentRequest
     */
    batchId?: string;
    /**
     * Overall Start Date Time
     * @type {string}
     * @memberof AssessmentRequest
     */
    startDateTime?: string;
    /**
     * Overall End Date Time
     * @type {string}
     * @memberof AssessmentRequest
     */
    endDateTime?: string;
    /**
     * Status
     * @type {string}
     * @memberof AssessmentRequest
     */
    status?: string;
    /**
     * List of Unique emailIds to which Assessment invitations are sent
     * @type {Array<string>}
     * @memberof AssessmentRequest
     */
    userEmailIds?: Array<string>;
    /**
     * Unique user id of the assessment admin
     * @type {string}
     * @memberof AssessmentRequest
     */
    assignedBy?: string;

    pagination?: PaginationModel;
}
