// tslint:disable
/**
 * UAP-Core Services
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Assessment Create/Update Object
 * @export
 * @interface CreateAssessmentRequest
 */
export interface CreateAssessmentRequest {
    packageId: string;
    /**
     * Unique batch id to group individual assessments
     * @type {string}
     * @memberof CreateAssessmentRequest
     */
    batchId?: string;
    /**
     * Overall Start Date Time
     * @type {string}
     * @memberof CreateAssessmentRequest
     */
    startDateTime?: string;
    /**
     * Overall End Date Time
     * @type {string}
     * @memberof CreateAssessmentRequest
     */
    endDateTime?: string;
    /**
     * Status
     * @type {string}
     * @memberof CreateAssessmentRequest
     */
    status?: string;
    /**
     * List of Unique emailIds to which Assessment invitations are sent
     * @type {Array<string>}
     * @memberof CreateAssessmentRequest
     */
    userEmailIds: Array<string>;
    /**
     * Unique user id of the assessment admin
     * @type {string}
     * @memberof CreateAssessmentRequest
     */
    assignedBy?: string;
}
