apiVersion: apps/v1
kind: Deployment
metadata:
  name: uapui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uapui
  template:
    metadata:
      labels:
        app: uapui
    spec:
      containers:
        - name: uapui
          image: unifiedassessprod.azurecr.io/uapui:$tag
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: mysecret